### ISSUE TITLE
Mögliche Aufstellorte

### ISSUE THREAD

**Issue by CFenner** [WHW-HD/Wetterstation#7]
1. Clubhaus WHW
- Strom vorhanden
- WiFi (?)
- Witterungsschutz (Werkstatt)
- eingeschränkter Wind
2. Steg WHW
- WiFi (?)
- evtl. eingeschränkter Wind
3. Steg SVH
- Strom vorhanden (?)
- WiFi (?)
- freier Wind

**Comment by anemojudit** [comment]
Statt SCH müsste es SVH (Seglervereinigung Heidelberg) heißen. (Nur damit wir die Vereine nicht verwechseln.)
WiFi müsste an beiden Orten durch die Heidelberger Hotspots gegeben sein. Ich probiere heute Abend mal aus. (Siehe heidelberg4you)

**Comment by CFenner** [comment]
Laut [Karte](http://www.meinheidelberg.de/desktop/index.html?category=Hotspots) könnte das beim SVH klappen. Der nächste Hotspot beim WHW ist allerdings auf der Bergheimer Str.

**Comment by anemojudit** [comment]
Ich hatte eine andere Karte gesehen:
http://www.heidelberg.de/site/Heidelberg_ROOT/get/documents_E-1256793866/heidelberg/Objektdatenbank/01/Bilder/01_uebersichtskarte_hotspots_by_.jpg

Mal sehen, wann die geplanten Spots kommen.

**Comment by CFenner** [comment]
Judith:
>Ich glaube nicht, dass man am WHW die Ernst-Waltz-Brücke einfangen kann, aber vielleicht draußen am Steg. Muss ich nochmal versuchen, gestern war ich nur am Bootshaus und da war nichts.

#6

**Comment by anemojudit** [comment]
**Protokoll Sitzung 1.2.2017** (Christopher, Felix, Ben, Judit)

1. Prototyp bauen bis Anfang April (Felix fängt an, dann Christopher weiter) = 1. Projektphase
2. Aufstellen am WHW und testen (Strom aus Steckdose) = Beginn 2. Phase
3. Entscheidung, ob am SVH oder WHW (Stegplatz suchen)
4. davon abhängig: Stromversorgung (Steckdose oder Solar mit Batterie); Montage

Arbeitsaufwand: 1. Phase 2 x 15 Stunden; 2. Phase: 2 x 30 St.; Wartung dauerhaft: 4 St. / Jahr
Sensoren: Windstärke, -richtung, Niederschlagsmenge, Temp. und Luftfeuchtigkeit (?); Wassertemperatur für Paddler (?); vieles ist möglich, was ist sinnvoll??

**Comment by anemojudit** [comment]
Weiterführende Links:
http://zieren.de/ip-anemometer/
http://www.surfsupcenter.de/DE/C/wetter/wetter.html (Profianlage fertig gekauft für ca. 1500,-; d.h. zu teuer für WHW)
